name: Deploy to DigitalOcean Droplet
'on':
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Clone Repo To DO Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          passphrase: ${{secrets.PASSPHRASE}}
          script: |
            pwd 
            ls
            cd ./No-Code-Web-Builder/backend
            git pull ${{secrets.REPO_ORIGIN}} develop
            npm install
            pm2 start ./No-Code-Web-Builder/backend/dist/app.js
            pm2 save
            pm2 startup
            
